name: Release

# Uncomment the following to let goreleaser automatically
# create a GitHub release when a tag is pushed.
# permissions:
#   contents: write

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
      # to be used by fork patch-releases ^^
      - 'v*.*.*-*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.20.x

      - name: Prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF#refs/tags/}
            echo ::set-output name=tag_name::${TAG}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: create goreleaser docker registry login file
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "docker-registry.json"
          json: ${{ secrets.DOCKER_REGISTRY_JSON }}
          
      - name: List files and present dir path
        run: |
            pwd 
            ls

      - name: Run GoReleaser
        run: |
            make release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_KEY }}
          DOCKER_REGISTRY: hub.docker.com
          DOCKER_CREDS_FILE: docker-registry.json
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB }}
          password: ${{ secrets.DOCKERHUB_KEY }}
          
      - name: List Docker images push manually
        run: |
            docker images